import assert from "node:assert/strict";
import test from "node:test";
import { to_jsstring, to_luastring } from "fengari";

// P1-14b: Lua strings reach a binding through luaStringToJs (LuaStrings.ts), which must give the
// exact text fengari's lossy decoder gives — `to_jsstring(bytes, 0, n, true)` — for any bytes.
const { luaStringToJs } = await import("../dist/code/browser/glue/LuaStrings.js");
const { GlueLuaVm } = await import("../dist/code/browser/glue/GlueLua.js");

function random(seed) {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const PIECES = [
  [0x61], [0x7a, 0x30, 0x20], [0x00], [0x7f],
  [...to_luastring("Восстановление")], [...to_luastring("€")], [...to_luastring("😀")],
  [0xef, 0xbb, 0xbf], // BOM
  [0xd0], [0xe2, 0x82], [0xf0, 0x9f, 0x98], // cut sequences
  [0xc0, 0x80], [0xc1, 0xbf], [0xe0, 0x80, 0x80], [0xf0, 0x80, 0x80, 0x80], // overlongs
  [0xed, 0xa0, 0x80], [0xed, 0xbf, 0xbf], // surrogates
  [0xf4, 0x90, 0x80, 0x80], [0xf5, 0x80, 0x80, 0x80], [0xff], [0x80], [0xbf, 0x61],
];

test("luaStringToJs equals fengari's lossy decoder on generated bytes", () => {
  const next = random(1405);
  for (let index = 0; index < 50000; index += 1) {
    const bytes = [];
    const count = Math.floor(next() * 8);
    for (let piece = 0; piece < count; piece += 1) {
      if (next() < 0.15) bytes.push(Math.floor(next() * 256));
      else bytes.push(...PIECES[Math.floor(next() * PIECES.length)]);
    }
    const u8 = Uint8Array.from(bytes);
    assert.equal(luaStringToJs(u8), to_jsstring(u8, 0, u8.length, true), `bytes ${bytes.join(",")}`);
  }
  // The short ASCII path, the long path and the boundary between them.
  for (const length of [0, 1, 15, 16, 17, 30, 200]) {
    const u8 = Uint8Array.from({ length }, (_, at) => 0x41 + (at % 26));
    assert.equal(luaStringToJs(u8), to_jsstring(u8, 0, length, true));
  }
  // A leading BOM survives, as fengari keeps it.
  assert.equal(luaStringToJs(Uint8Array.from([0xef, 0xbb, 0xbf, 0x61])), "﻿a");
});

test("a 30-byte ASCII argument crosses into a binding without a String.fromCharCode per byte", () => {
  const vm = new GlueLuaVm();
  const seen = [];
  vm.registerGlobal("StringProbe", (args) => { seen.push(args[0], args[1]); return []; });
  const fn = vm.compileFunction('StringProbe("abcdefghijklmnopqrstuvwxyz0123", "Восстановление сил")', "string-probe", []);
  const original = String.fromCharCode;
  let calls = 0;
  String.fromCharCode = function (...codes) { calls += 1; return original.apply(this, codes); };
  try { vm.call(fn); } finally { String.fromCharCode = original; }
  assert.deepEqual(seen, ["abcdefghijklmnopqrstuvwxyz0123", "Восстановление сил"]);
  assert.ok(calls <= 1, `String.fromCharCode called ${calls} times`);
  vm.release(fn);
  vm.close();
});
